=== TerraFirmaGreg-Team/AutoPack-Director/modules/core/src/main/resources/schemas/bundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/TerraFirmaGreg-Team/AutoPack-Director/refs/heads/main/modules/core/src/main/resources/schemas/bundle.schema.json",
  "title": "Bundle of remote mods and modify ops",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "curse": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "modrinth": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "url": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "modify": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}

=== TerraFirmaGreg-Team/AutoPack-Director/modules/core/src/test/resources/config/example.bundle.json
{
  "curse": [
    {
      "addonId": 1,
      "fileId": 2
    }
  ],
  "modrinth": [
    {
      "addonId": "project-slug",
      "fileId": "version-1",
      "fileIndex": 0
    }
  ],
  "url": [
    {
      "url": "https://example.com/bundle-mod.jar",
      "fileName": "bundle-mod.jar"
    }
  ],
  "modify": [
    {
      "fileName": "old-mod.jar",
      "folder": "mods",
      "disable": true
    }
  ]
}
